### ISSUE TITLE
How to Insert script with Google Tag Manager

### ISSUE THREAD

**Issue by shatuhi** [AppsFlyerSDK/appsflyer-onelink-smart-script#3]
Hi There,

Would you tell me how to insert script with Google Tag Manager.

The script didn't work after the insertion.

Here's the Screenshot as follow.
<img width="1180" alt="GTM1" src="https://user-images.githubusercontent.com/50195708/134793026-7d0a7d02-9bf9-45a9-91d6-5d8d1aaced93.png">

From a marketing man who is not familiar with website code.

**Comment by liaz-af** [comment]
Hello, 
Unfortunately, the script doesn't support triggering using Google Tag Manager.
You can find out more about using Smart Script [here](https://dev.appsflyer.com/hc/docs/onelink-smart-script).

Cheers
